NAME = Glass
TYPE = SHARED
SRCS = GlassDecorator.cpp GlassAddOn.cpp
LIBS = be
LIBPATHS = /boot/system/servers
SYSTEM_INCLUDE_PATHS = /boot/system/develop/headers/private/interface /boot/system/develop/headers/private/app
OPTIMIZE = FULL

include /boot/system/develop/etc/makefile-engine
